#ifndef __RCC_H__
#define __RCC_H__

#define RCC_BASE_ADDRESS (0x40023800)
typedef struct rcc {
	volatile uint32_t CR, PLLCFGR, CFGR, CIR, AHB1RSTR, AHB2RSTR, AHB3RSTR, RESERVED0, APB1RSTR, APB2RSTR, RESERVED1[2], AHB1ENR, AHB2ENR, AHB3ENR, RESERVED2, APB1ENR, APB2ENR, RESERVED3[2], AHB1LPENR, AHB2LPENR, AHB3LPENR, RESERVED4, APB1LPENR, APB2LPENR, RESERVED5[2], BDCR, CSR, RESERVED6[2], SSCGR, PLLI2SCFGR, PLLSAICFGR, DCKCFGR, CKGATENR, DCKCFGR2;
} rcc_t;
#define RCC ((rcc_t*) RCC_BASE_ADDRESS)


#endif
